({
	'bold': 'Negrito\n',
	'copy': 'Copiar\n',
	'cut': 'Recortar\n',
	'delete': 'Excluir ',
	'indent': 'Recuar\n',
	'insertHorizontalRule': 'Régua Horizontal\n',
	'insertOrderedList': 'Lista Numerada',
	'insertUnorderedList': 'Lista com Marcadores',
	'italic': 'Itálico\n',
	'justifyCenter': 'Alinhar pelo Centro',
	'justifyFull': 'Justificar\n',
	'justifyLeft': 'Alinhar pela Esquerda\n',
	'justifyRight': 'Alinhar pela Direita\n',
	'outdent': 'Não-chanfrado',
	'paste': 'Colar\n',
	'redo': 'Refazer\n',
	'removeFormat': 'Remover Formato',
	'selectAll': 'Selecionar Todos\n',
	'strikethrough': 'Tachado',
	'subscript': 'Subscrito\n',
	'superscript': 'Sobrescrito\n',
	'underline': 'Sublinhado\n',
	'undo': 'Desfazer\n',
	'unlink': 'Remover Link\n',
	'createLink': 'Criar Link',
	'insertImage': 'Inserir Imagem\n',
	'insertTable': 'Inserir/Editar Tabela',
	'toggleTableBorder': 'Alternar Moldura da Tabela',
	'deleteTable': 'Excluir Tabela',
	'tableProp': 'Propriedade da Tabela',
	'htmlToggle': 'Origem HTML\n',
	'foreColor': 'Cor do Primeiro Plano',
	'hiliteColor': 'Cor de segundo plano\n',
	'plainFormatBlock': 'Estilo de Parágrafo',
	'formatBlock': 'Estilo de Parágrafo',
	'fontSize': 'Tamanho da Fonte',
	'fontName': 'Nome da Fonte',
	/* Error messages */
	'copyErrorFF': 'A ação de cópia está disponível apenas no Firefox por meio do atalho pelo teclado em razão de sua decisão de design: utilize ctrl+c.',
	'cutErrorFF': 'A ação de recorte está disponível apenas no Firefox por meio do atalho pelo teclado em razão de sua decisão de design: utilize ctrl+x.',
	'pasteErrorFF': 'A ação de cola está disponível apenas no Firefox por meio do atalho pelo teclado em razão de sua decisão de design: utilize ctrl+v.'
})
