console.warn("dijit.dijit may dissapear in the 0.9 timeframe in lieu of a different rollup file!");
dojo.provide("dijit.dijit");
dojo.require("dijit.base.Widget");
dojo.require("dijit.base.Layout");
dojo.require("dijit.base.Container");
dojo.require("dijit.form._FormWidget");
dojo.require("dijit.base.TemplatedWidget");
dojo.require("dojo.parser");
dojo.require("dijit.util.manager");
dojo.require("dijit.util.wai");
dojo.require("dijit.util.focus");
dojo.require("dijit.util.popup");
dojo.require("dijit.util.place");
