({
	'bold': 'Fett',
	'copy': 'Kopieren',
	'cut': 'Ausschneiden',
	'delete': 'Löschen',
	'indent': 'Einrücken',
	'insertHorizontalRule': 'Horizontaler Strich',
	'insertOrderedList': 'Nummerierte Liste',
	'insertUnorderedList': 'Listenpunkte',
	'italic': 'Kursiv',
	'justifyCenter': 'Zentrieren',
	'justifyFull': 'Blocksatz',
	'justifyLeft': 'Linksbündig',
	'justifyRight': 'Rechtsbündig',
	'outdent': 'Ausrücken',
	'paste': 'Einfügen',
	'redo': 'Wiederherstellen',
	'removeFormat': 'Formatierung entfernen',
	'selectAll': 'Alles auswählen',
	'strikethrough': 'Durchgestrichen',
	'subscript': 'Tiefgestellt',
	'superscript': 'Hochgestellt',
	'underline': 'Unterstrichen',
	'undo': 'Rückgängig',
	'unlink': 'Link entfernen',
	'createLink': 'Link erstellen',
	'insertImage': 'Grafik einfügen',
	'insertTable': 'Tabelle einfügen/bearbeiten',
	'toggleTableBorder': 'Tabellenumrandung ein-/ausschalten',
	'deleteTable': 'Tabelle löschen',
	'tableProp': 'Tabelleneigenschaft',
	'htmlToggle': 'HTML-Quelltext',
	'foreColor': 'Vordergrundfarbe',
	'hiliteColor': 'Hintergrundfarbe',
	'plainFormatBlock': 'Absatzstil',
	'formatBlock': 'Absatzstil',
	'fontSize': 'Schriftgröße',
	'fontName': 'Schriftartname',
	/* Error messages */
	'systemShortcutFF': 'Die Aktion "${0}" ist in Mozilla Firefox nur über einen Tastaturkurzbefehl verfügbar. Verwenden Sie ${1}.',
	'ctrlKey':'Strg+${0}'
})
