({
	'bold': 'Negrito',
	'copy': 'Copiar',
	'cut': 'Recortar',
	'delete': 'Excluir',
	'indent': 'Indentar',
	'insertHorizontalRule': 'Régua Horizontal',
	'insertOrderedList': 'Lista Numerada',
	'insertUnorderedList': 'Lista com Marcadores',
	'italic': 'Itálico',
	'justifyCenter': 'Alinhar no Centro',
	'justifyFull': 'Justificar',
	'justifyLeft': 'Alinhar à Esquerda',
	'justifyRight': 'Alinhar à Direita',
	'outdent': 'Remover Indentação',
	'paste': 'Colar',
	'redo': 'Refazer',
	'removeFormat': 'Remover Formato',
	'selectAll': 'Selecionar Tudo',
	'strikethrough': 'Tachado',
	'subscript': 'Subscrito',
	'superscript': 'Sobrescrito',
	'underline': 'Sublinhado',
	'undo': 'Desfazer',
	'unlink': 'Remover Link',
	'createLink': 'Criar Link',
	'toggleDir': 'Alternar Direção',
	'insertImage': 'Inserir Imagem',
	'insertTable': 'Inserir/Editar Tabela',
	'toggleTableBorder': 'Alternar Borda da Tabela',
	'deleteTable': 'Excluir Tabela',
	'tableProp': 'Propriedade da Tabela',
	'htmlToggle': 'Fonte HTML',
	'foreColor': 'Cor de Primeiro Plano',
	'hiliteColor': 'Cor do Segundo Plano',
	'plainFormatBlock': 'Estilo de Parágrafo',
	'formatBlock': 'Estilo de Parágrafo',
	'fontSize': 'Tamanho da Fonte',
	'fontName': 'Nome da Fonte',
	'tabIndent': 'Indentação de Tabulação',
	/* Error messages */
	'systemShortcut': 'A ação "${0}" está disponível no seu navegador apenas usando um atalho de teclado. Use ${1}.'
})
