({
	'bold': 'Negrita',
	'copy': 'Copiar',
	'cut': 'Cortar',
	'delete': 'Suprimir',
	'indent': 'Sangría',
	'insertHorizontalRule': 'Regla horizontal',
	'insertOrderedList': 'Lista numerada',
	'insertUnorderedList': 'Lista con viñetas',
	'italic': 'Cursiva',
	'justifyCenter': 'Alinear centro',
	'justifyFull': 'Justificar',
	'justifyLeft': 'Alinear izquierda',
	'justifyRight': 'Alinear derecha',
	'outdent': 'Anular sangría',
	'paste': 'Pegar',
	'redo': 'Rehacer',
	'removeFormat': 'Eliminar formato',
	'selectAll': 'Seleccionar todo',
	'strikethrough': 'Tachado',
	'subscript': 'Subíndice',
	'superscript': 'Superíndice',
	'underline': 'Subrayado',
	'undo': 'Deshacer',
	'unlink': 'Eliminar enlace',
	'createLink': 'Crear enlace',
	'insertImage': 'Insertar imagen',
	'insertTable': 'Insertar/Editar tabla',
	'toggleTableBorder': 'Conmutar borde de tabla',
	'deleteTable': 'Suprimir tabla',
	'tableProp': 'Propiedad de tabla',
	'htmlToggle': 'Fuente HTML',
	'foreColor': 'Color de primer plano',
	'hiliteColor': 'Color de segundo plano',
	'plainFormatBlock': 'Estilo de párrafo',
	'formatBlock': 'Estilo de párrafo',
	'fontSize': 'Tamaño de font',
	'fontName': 'Nombre de font',
	/* Error messages */
	'copyErrorFF': 'La acción Copiar sólo está disponible en Firefox mediante un atajo de teclado debido a su diseño: utilice Control+C.',
	'cutErrorFF': 'La acción Cortar sólo está disponible en Firefox mediante un atajo de teclado debido a su diseño: utilice Control+X.',
	'pasteErrorFF': 'La acción Pegar sólo está disponible en Firefox mediante un atajo de teclado debido a su diseño: utilice Control+V.'
})
