({
	'bold': 'Grassetto',
	'copy': 'Copia',
	'cut': 'Taglia',
	'delete': 'Elimina',
	'indent': 'Aumenta Rientro',
	'insertHorizontalRule': 'Righello Orizzontale',
	'insertOrderedList': 'Lista Numerata',
	'insertUnorderedList': 'Lista Puntata',
	'italic': 'Corsivo',
	'justifyCenter': 'Allinea al Centro',
	'justifyFull': 'Giustifica',
	'justifyLeft': 'Allinea a Sinistra',
	'justifyRight': 'Allinea a Destra',
	'outdent': 'Riduci Rientro',
	'paste': 'Incolla',
	'redo': 'Ripeti',
	'removeFormat': 'Rimuovi Formato',
	'selectAll': 'Seleziona Tutto',
	'strikethrough': 'Barrato',
	'subscript': 'Pedice',
	'superscript': 'Apice',
	'underline': 'Sottolineato',
	'undo': 'Annulla',
	'unlink': 'Rimuovi Collegamento',
	'createLink': 'Crea collegamento',
	'insertImage': 'Inserisci Immagine',
	'htmlToggle': 'Sorgente HTML',
	'foreColor': 'Colore Primo Piano',
	'hiliteColor': 'Colore Sfondo',
	'plainFormatBlock': 'Stile Paragrafo',
	'formatBlock': 'Stile Paragrafo',
	'fontSize': 'Dimensioni Font',
	'fontName': 'Nome Font'
})
