({
	'bold': 'Grassetto',
	'copy': 'Copia',
	'cut': 'Taglia',
	'delete': 'Elimina',
	'indent': 'Aumenta Rientro',
	'inserthorizontalrule': 'Righello Orizzontale',
	'insertorderedlist': 'Lista Numerata',
	'insertunorderedlist': 'Lista Puntata',
	'italic': 'Corsivo',
	'justifycenter': 'Allinea al Centro',
	'justifyfull': 'Giustifica',
	'justifyleft': 'Allinea a Sinistra',
	'justifyright': 'Allinea a Destra',
	'outdent': 'Riduci Rientro',
	'paste': 'Incolla',
	'redo': 'Ripeti',
	'removeformat': 'Rimuovi Formato',
	'selectall': 'Seleziona Tutto',
	'strikethrough': 'Barrato',
	'subscript': 'Pedice',
	'superscript': 'Apice',
	'underline': 'Sottolineato',
	'undo': 'Annulla',
	'unlink': 'Rimuovi Collegamento',
	'createlink': 'Crea collegamento',
	'insertimage': 'Inserisci Immagine',
	'htmltoggle': 'Sorgente HTML',
	'forecolor': 'Colore Primo Piano',
	'hilitecolor': 'Colore Sfondo',
	'plainformatblock': 'Stile Paragrafo',
	'formatblock': 'Stile Paragrafo',
	'fontsize': 'Dimensioni Font',
	'fontname': 'Nome Font'
})
