({
	'bold': 'Fett',
	'copy': 'Kopieren',
	'cut': 'Ausschneiden',
	'delete': 'Löschen',
	'indent': 'Einrücken',
	'inserthorizontalrule': 'Horizontale Linie',
	'insertorderedlist': 'Nummerierung',
	'insertunorderedlist': 'Auflistung',
	'italic': 'Kursiv',
	'justifycenter': 'Zentiert',
	'justifyfull': 'Blocksatz',
	'justifyleft': 'Linksbündig',
	'justifyright': 'Rechtsbündig',
	'outdent': 'Ausrücken',
	'paste': 'Einfügen',
	'redo': 'Wiederholen',
	'removeformat': 'Formatierung löschen',
	'selectall': 'Alles auswählen',
	'strikethrough': 'Durchgestrichen',
	'subscript': 'Tiefgestellt',
	'superscript': 'Hochgestellt',
	'underline': 'Unterstrichen',
	'undo': 'Rückgängig',
	'unlink': 'Link löschen',
	'createlink': 'Link erstellen',
	'insertimage': 'Bild einfügen',
//	'htmltoggle': 'HTML Source',
	'forecolor': 'Textfarbe',
	'hilitecolor': 'Hintergrundfarbe',
	'plainformatblock': 'Paragraph Stil',
	'formatblock': 'Paragraph Stil',
	'fontsize': 'Schriftgröße',
	'fontname': 'Schriftart'
})
