({
	'bold': 'Fett',
	'copy': 'Kopieren',
	'cut': 'Ausschneiden',
	'delete': 'Löschen',
	'indent': 'Einrücken',
	'insertHorizontalRule': 'Horizontale Linie',
	'insertOrderedList': 'Nummerierung',
	'insertUnorderedList': 'Auflistung',
	'italic': 'Kursiv',
	'justifyCenter': 'Zentiert',
	'justifyFull': 'Blocksatz',
	'justifyLeft': 'Linksbündig',
	'justifyRight': 'Rechtsbündig',
	'outdent': 'Ausrücken',
	'paste': 'Einfügen',
	'redo': 'Wiederholen',
	'removeFormat': 'Formatierung löschen',
	'selectAll': 'Alles auswählen',
	'strikethrough': 'Durchgestrichen',
	'subscript': 'Tiefgestellt',
	'superscript': 'Hochgestellt',
	'underline': 'Unterstrichen',
	'undo': 'Rückgängig',
	'unlink': 'Link löschen',
	'createLink': 'Link erstellen',
	'insertImage': 'Bild einfügen',
//	'htmlToggle': 'HTML Source',
	'foreColor': 'Textfarbe',
	'hiliteColor': 'Hintergrundfarbe',
	'plainFormatBlock': 'Paragraph Stil',
	'formatBlock': 'Paragraph Stil',
	'fontSize': 'Schriftgröße',
	'fontName': 'Schriftart'
})
