({
	'bold': 'Félkövér',
	'copy': 'Másolás',
	'cut': 'Kivágás',
	'delete': 'Törlés',
	'indent': 'Behúzás',
	'insertHorizontalRule': 'Vízszintes vonalzó',
	'insertOrderedList': 'Számozott lista',
	'insertUnorderedList': 'Felsorolásjeles lista',
	'italic': 'Dőlt',
	'justifyCenter': 'Középre igazítás',
	'justifyFull': 'Sorkizárás',
	'justifyLeft': 'Balra igazítás',
	'justifyRight': 'Jobbra igazítás',
	'outdent': 'Negatív behúzás',
	'paste': 'Beillesztés',
	'redo': 'Újra',
	'removeFormat': 'Formázás eltávolítása',
	'selectAll': 'Összes kijelölése',
	'strikethrough': 'Áthúzott',
	'subscript': 'Alsó index',
	'superscript': 'Felső index',
	'underline': 'Aláhúzott',
	'undo': 'Visszavonás',
	'unlink': 'Hivatkozás eltávolítása',
	'createLink': 'Hivatkozás létrehozása',
	'toggleDir': 'Irányváltás',
	'insertImage': 'Kép beszúrása',
	'insertTable': 'Táblázat beszúrása/szerkesztése',
	'toggleTableBorder': 'Táblázatszegély ki-/bekapcsolása',
	'deleteTable': 'Táblázat törlése',
	'tableProp': 'Táblázat tulajdonságai',
	'htmlToggle': 'HTML forrás',
	'foreColor': 'Előtérszín',
	'hiliteColor': 'Háttérszín',
	'plainFormatBlock': 'Bekezdés stílusa',
	'formatBlock': 'Bekezdés stílusa',
	'fontSize': 'Betűméret',
	'fontName': 'Betűtípus',
	'tabIndent': 'Tabulátor behúzás',
	/* Error messages */
	'systemShortcut': 'A(z) "${0}" művelet csak billentyűparancs használatával érhető el a böngészőben. Használja a következő gyorsbillentyűt: ${1}.'
})
