({
	'bold': 'Krepko',
	'copy': 'Prekopiraj',
	'cut': 'Izreži',
	'delete': 'Izbriši',
	'indent': 'Zamik',
	'insertHorizontalRule': 'Vodoravno pravilo',
	'insertOrderedList': 'Oštevilčen seznam',
	'insertUnorderedList': 'Naštevni seznam',
	'italic': 'Ležeče',
	'justifyCenter': 'Poravnaj sredinsko',
	'justifyFull': 'Obojestranska poravnava',
	'justifyLeft': 'Poravnaj levo',
	'justifyRight': 'Poravnaj desno',
	'outdent': 'Viseči odstavek',
	'paste': 'Prilepi',
	'redo': 'Znova uveljavi',
	'removeFormat': 'Odstrani oblikovanje',
	'selectAll': 'Izberi vse',
	'strikethrough': 'Prečrtano',
	'subscript': 'Podpisano',
	'superscript': 'Nadpisano',
	'underline': 'Podčrtano',
	'undo': 'Razveljavi',
	'unlink': 'Odstrani povezavo',
	'createLink': 'Izdelaj povezavo',
	'toggleDir': 'Preklopi smer',
	'insertImage': 'Vstavi sliko',
	'insertTable': 'Vstavi/uredi tabelo',
	'toggleTableBorder': 'Preklopi obrobo tabele',
	'deleteTable': 'Izbriši tabelo',
	'tableProp': 'Lastnost tabele',
	'htmlToggle': 'Izvor HTML',
	'foreColor': 'Barva ospredja',
	'hiliteColor': 'Barva ozadja',
	'plainFormatBlock': 'Slog odstavka',
	'formatBlock': 'Slog odstavka',
	'fontSize': 'Velikost pisave',
	'fontName': 'Ime pisave',
	/* Error messages */
	'systemShortcutFF': 'Dejanje "${0}" je na voljo samo v brskalniku Mozilla Firefox prek bližnjic na tipkovnici. Uporabite ${1}.'
})

