({
	'bold': 'Aldin',
	'copy': 'Copiere',
	'cut': 'Tăiere',
	'delete': 'Ştergere',
	'indent': 'Indentare',
	'insertHorizontalRule': 'Linie delimitatoare',
	'insertOrderedList': 'Listă numerotată',
	'insertUnorderedList': 'Listă cu marcator',
	'italic': 'Cursiv',
	'justifyCenter': 'Aliniere centru',
	'justifyFull': 'Justify',
	'justifyLeft': 'Aliniere stânga',
	'justifyRight': 'Aliniere dreapta',
	'outdent': 'Outdent',
	'paste': 'Lipire',
	'redo': 'Refacere',
	'removeFormat': 'Înlăturare format',
	'selectAll': 'Selectează tot',
	'strikethrough': 'Tăiere',
	'subscript': 'Scriere indice inferior',
	'superscript': 'Scriere indice superior',
	'underline': 'Liniuţă de subliniere',
	'undo': 'Anulare acţiune',
	'unlink': 'Înlăturare legătură',
	'createLink': 'Creare legătură',
	'toggleDir': 'Comutare direcţie',
	'insertImage': 'Inserare imagine',
	'insertTable': 'Inserare/Editare tabelă',
	'toggleTableBorder': 'Comutare bordură tabelă',
	'deleteTable': 'Ştergere tabelă',
	'tableProp': 'Proprietate tabelă',
	'htmlToggle': 'Sursă HTML',
	'foreColor': 'Culoare de prim-plan',
	'hiliteColor': 'Culoare de fundal',
	'plainFormatBlock': 'Stil paragraf',
	'formatBlock': 'Stil paragraf',
	'fontSize': 'Dimensiune font',
	'fontName': 'Nume font',
	'tabIndent': 'Indentare Tab',
	"fullScreen": "Comutare ecran complet",
	"viewSource": "Vizualizara sursă HTML",
	"print": "Tipărire",
	"newPage": "Pagină nouă",
	/* Error messages */
	'systemShortcut': 'Acţiunea "${0}" este disponibilă în browser-ul dvs. doar utilizând o comandă rapidă de la tastatură. Utilizaţi ${1}.'
})

